companieshouse/psc-discrepancies.web.ch.gov.uk

Makefile
Got rid of the line that deletes the package.json and package-lock.json files as these are needed for a Javascript node implementation
=> Remove deletion of package.json

package.json, server/app.js, start.sh
Remove gulp from package.json as this shouldn't be part of starting app in e2e environments
Add NODE_PORT to mesos start so it uses the port number passed into script
=> Update start script

server/lib/validation/error_manifest.js, server/lib/validation/index.js, server/routes/report.js, server/views/report/company_number.njk, test/server/lib/validation/index.test.js, test/server/routes/report.test.js
Added page to enable entry of company number
Added validation to check for blank, undefined, null company numbers as well as numbers that are not 8 characters long
Added tests for the validator and the page
Amended the `describe` value of the validation test class to properly describe the class
Added error_manifest entries for the company number error messages
Covers stories FAML-251, FAML-240
=> Add company number page

server/routes/report.js, server/services/psc_discrepancy.js, test/env.js, test/server/services/psc_discrepancy.test.js
API integration issues not reproducible in vagrant have been fixed, namely:
- Add `authorization` header in the request payload
- Use `err.status` in addition to `err.statusCode` to handle exceptions
- Update unit tests to reflect change in code state
=> Fix: Straighten out API integration gremlins in TEST environment

server/routes/report.js, server/services/psc_discrepancy.js, test/server/_fakes/data/services/psc_discrepancy.js, test/server/routes/report.test.js, test/server/services/psc_discrepancy.test.js
- Submit a 'COMPLETE' status for the report after details are successfully POSTed
- Add unit tests to cover the extra code paths
- Remove report data from session after submission
=> Feature/FAML-376: Submit report status

server/services/psc_discrepancy.js, test/server/services/psc_discrepancy.test.js
- Ensures our baseOptions are returned by method call and not pre-set in the constructor
- This avoids reusing mutated module-wide objects in subsequent requests
- Includes updated tests to reflect code changes
#FAML-415
=> Fix: Intermittent server error when POSTing the email

server/lib/Session.js, server/lib/validation/index.js, server/routes/report.js, server/services/psc_discrepancy.js, test/env.js, test/server/lib/validation/index.test.js, test/server/routes/report.test.js, test/server/services/psc_discrepancy.test.js
Extend the remit of our logs to cover client and service requests, not just error scenarios
=> Feature: Add liberal logging to the service

server/config/winston.js, server/lib/Utility.js, server/lib/errors/error_manifest.js, server/lib/validation/index.js, server/routes/report.js, server/services/psc_discrepancy.js, server/views/report/company_number.njk, server/views/report/contact_name.njk, test/server/_fakes/data/services/psc_discrepancy.js, test/server/_fakes/mocks/lib/session.js, test/server/lib/Session.test.js, test/server/lib/Utility.test.js, test/server/lib/validation/index.test.js, test/server/routes/report.test.js, test/server/routes/utils/index.test.js, test/server/services/psc_discrepancy.test.js
Includes:
- refactor of user journey to have contact name as first form
- tweaks to Utility logger to account for an error stack that is an object
- refactor of Winston logger to properly deal with JSON for the console transport
- tests to cover new functionality
- unit test coverage bump elsewhere
Covers #FAML-377 and #FAML-416
=> Feature/FAML-377: Submit contact name to API

package-lock.json, package.json
To avoid breaking changes when new code is merged into master, the session-handler's Git Link in package.json needs to be pegged to a specific version. This versioning feature has now been introduced to the session-handler at our request
#FAML-Quick-Fix
=> Fix: Peg session-handler to specific version

server/routes/report.js, server/views/report/oe_email.njk
Pre-fills phoneNumber field on the obliged entity contact page with phoneNumber (if available), and not the email as is currently the case..
Also trims white spaces from both ends of the phone number.
Completes #FAML-310
=> Fix: Pre-fill phoneNumber field with phoneNumber, not email

server/routes/report.js
After a report submission has completed, ensure we reset session data for report specific fields only
=> Fix: Reset session data for initialServiceResponse field only

.eslintrc, package-lock.json, package.json, test/env.js, test/server/_fakes/data/services/psc_discrepancy.js, test/server/_fakes/mocks/lib/session.js, test/server/lib/Session.test.js, test/server/lib/Utility.test.js, test/server/lib/validation/index.test.js, test/server/routes/report.test.js, test/server/routes/utils/index.test.js, test/server/services/psc_discrepancy.test.js, test/setup.js
Previously, Linting only covered the `server` directory. This task extends that cover to the `test` directory as well
#FAML-429
=> Chore: Fix all Linting issues for the test directory

app/src/scss/__global.scss, app/src/scss/partials/_footer.scss, server/routes/report.js, server/views/_partials/__footer.njk, server/views/_partials/phase_banner.njk, server/views/report/company_number.njk, server/views/report/contact_name.njk, server/views/report/discrepancy_details.njk, server/views/report/oe_email.njk, server/views/report/oe_type.njk, server/views/report/organisation_name.njk
- Add title to every page
- Use correct syntax for form elements
- Ensure summary error messages link through to complementary inline errors
- Also includes spacing around variables in templates for better legibility
=> Fix/FAML-454: Straighten out accessibility issues

server/services/data/oe_types.js
Removes trailing 's' from Trust description
=> Fix/FAML-470: Remove trailing 's' from Trust description

server/routes/report.js, server/views/report/error.njk, test/server/routes/report.test.js
If I path is not mapped for the `report-a-discrepancy` root then an error page will be displayed
Resolves: FAML-390
=> Add error page for paths which are not mapped

server/views/report/psc_name.njk
This fixes the missing 'Or' in Psc list
=> fix: include expression to check for object length in template

server/routes/report.js
Shows missing organisation name on PSC names page..
=> fix: show missing organisation name on PSC page

server/routes/report.js, server/views/report/discrepancy_details.njk, test/server/routes/report.test.js
feature:
-added routing from details to check-your-answers
-added a basic post route from check-your-answers to confirmation that will be completed in faml-640
-changed submit text on button and declaration on details page to reflect that details will be submitted on check-your-answers.
- details are now saved to the session.
Jira ticket: https://companieshouse.atlassian.net/browse/FAML-634
=> Implement 'Continue' for entering into "Check your answers" page

server/routes/utils/index.js, test/server/routes/utils/index.test.js
fixed- service name changed to match prototype
from "PSC discrepancies" 
to "Report a discrepancy about a beneficial owner on the PSC register"
=> fixed- service name changed to match prototype

server/views/report/psc_discrepancy_types.njk, server/views/report/psc_name.njk
Added On Click events capturing user input information to submit buttons for Psc Name and Type pages.
https://companieshouse.atlassian.net/browse/FAML-665
=> feature: Matomo events on psc names and discrepancy types

package.json, server/app.js, server/views/_layouts/default.njk, server/views/_partials/cookie-consent-banner.njk
-add cookie-consent-banner.njk
-upgraded govuk-frontend up to 3.11.0
-added chsurl to be able to access cookie help page
-updated default.njk to include cookie-consent-banner.njk
=> bi-6972-cookie-consent investigation
