companieshouse/psc-discrepancies.web.ch.gov.uk

- package.json
Sets version of ESLint to latest
> chore: bump up ESLint version to latest

- Makefile
- routes.yaml
Add missing build tag
Add ^ to urls in routes.yaml
> Add missing build tag

- Makefile
Remove copy from dist folder and copy everything from root of web app
> Remove dist copy

- Makefile
Update copy command to copy all files and folders to the build folder but excluding the build folder itself
Removed the delete command of the dist folder as not required
> Change copy command

- Makefile
Rename the artifact name to match the application name
Remove the version variable. It's not required as the version is extracted from the version file
> Amend makefile

- start.sh
Update the application start command to use npm start as this is a Javascript application not Typescript
> Update how to start application

- start.sh
Update start script to load in local environment variables and then set the NODE_PORT to the port number passed into the script.
Change to use node server.js to start the app
> Amend start command for app

- server/routes/report.js
- server/views/report/discrepancy_details.njk
- test/server/routes/report.test.js
Add discrepancy details page to the application
Create discrepancy details template
Add route handler
Add unit test
FAML-290
> Add discrepancy details page

- app/src/scss/report.scss
- gulpfile.js
- server/app.js
- server/config/.env
- server/config/.env.example
- server/router.js
- server/views/_layouts/default.njk
- server/views/_partials/__footer.njk
Segregates CDN set-up for the different asset classes to reflect production CDN
#FAML-363
> Feature: Additional CDN set-up

- server/app.js
- server/lib/validation/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/views/report/index.njk
- server/views/report/oe_email.njk
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
- Adds tests for the email validation feature
- Covers both happy and unhappy paths
#FAML-327
> Test: Obliged entity email validation tests

- server/lib/validation/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/views/report/discrepancy_details.njk
- server/views/report/oe_email.njk
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
Add new method to validation/index.js that validates the discrepancy details is populated and containts alphabetic characters
Add post endpoint for discrepancy details to report.js
Add error classes to deiscrepancy_details.njk
Add unit tests
FAML-341
> Add validation to discrepancy details screen

- app/src/scss/__global.scss
- server/app.js
- server/router.js
- server/views/_partials/__footer.njk
- server/views/_partials/banner.njk
- Removes wild-card character for the 'Access-Control-Allow-Origin' header
- De-references the /assets path in app.js
#FAML-363
> Fix: Change default assets path is scss

- server/lib/validation/index.js
Add initialisation of this.errors in all validation methods
FAML-341
> Stop multiple errors in summary

- server/views/report/company_number.njk
Amended page layout as the page content was appearing as though it was part of the footer
> Amended page layout

- .eslintrc
- package.json
- server/app.js
- server/config/winston.js
- server/router.js
- server/routes/report.js
- Uses the standardJS ruleset as our baseline, inline with GovUk guidelines and standards
- Adds/overrides one extra rule only i.e. enforce the use semi-colons as statement terminators
- Adds husky to the project
- Husky allows for a more transparent means by which to add git hooks
FAML-358
> Feature: Add revised linting approach to the web service

- server/lib/validation/error_manifest.js
- server/lib/validation/index.js
- test/server/lib/validation/index.test.js
Amended email validation to enable the generation of different errors depending on validation failure.
Amended test coverage to cater for multiple scenarios for email errors
Done as part of FAML-385
> Enable multiple email error message scenarios

- server/config/.env
- server/config/.env.example
- server/lib/errors/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/services/psc_discrepancy.js
- server/views/report/oe_email.njk
- test/env.js
- test/server/_fakeData/services/psc_discrepancy_report.js
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
- test/server/services/psc_discrepancy.test.js
- test/setup.js
Interfaces with API to save Obliged Entity email
#FAML-382
> Feature/FAML-382: Save Obliged Entity Email via API

- server/routes/report.js
- server/services/psc_discrepancy.js
- test/server/services/psc_discrepancy.test.js
Fixes issues with failing API call for email screen
> bug: use correct email key for API payload

- server/routes/report.js
- server/services/psc_discrepancy.js
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/_fakes/mocks/lib/session.js
- test/server/routes/report.test.js
- test/server/services/psc_discrepancy.test.js
- Adds functionality to save a company number to the PSC service
- Includes updated tests for the new functionality
#FAML-366
> Feature/FAML-366: Save company number to service

- server/lib/validation/index.js
Update regex validation for contact name to use CH charset 2
FAML-252
> Update regex to use CharSet2

- server/lib/validation/index.js
Add missing en dash to regex for contact name
FAML-252
> Add missing en dash

- server/config/.env
- server/routes/report.js
- server/services/psc_discrepancy.js
- server/views/report/oe_email.njk
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/routes/report.test.js
- Functionality for telephone number to be saved to API
- Updated tests to cater for this new functionality
#FAML-310
> Feature: Add telephone number to contact page

- README.md
- package.json
Update the project README as part of the documentation effort.
#FAML-411
> Feature/FAML-411: Update README

- README.md
Add missing Redis section to the README
> Chore: Add section on Redis

- .gitignore
- package-lock.json
- package.json
- sonar-project.properties
Plugin SonarQube to the project.
#FAML-428
> Test: Integrate with sonarqube

- README.md
Minor copy change for the README
> Feature/FAML-411: Minor README tweak

- server/lib/errors/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/services/data/oe_types.js
- server/services/psc_discrepancy.js
- server/views/report/index.njk
- server/views/report/oe_type.njk
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/_fakes/mocks/lib/session.js
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
- test/server/services/psc_discrepancy.test.js
> Feature: Add ability to select obliged entity type

- server/lib/errors/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/services/psc_discrepancy.js
- server/views/report/index.njk
- server/views/report/organisation_name.njk
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
- test/server/services/psc_discrepancy.test.js
> feature: add ability to store a valid organisation name

- server/services/data/oe_types.js
Added another OE type to enumeration list for Obliged entities
> Feature/FAML-470: Additional Obliged Entity type to enumeration list

- package-lock.json
- package.json
- server/lib/Utility.js
- server/lib/validation/index.js
- server/routes/report.js
- server/services/psc_discrepancy.js
- server/views/_partials/error_summary.njk
- server/views/report/company_number.njk
- server/views/report/confirmation.njk
- server/views/report/contact_name.njk
- server/views/report/discrepancy_details.njk
- server/views/report/oe_email.njk
- server/views/report/oe_type.njk
- server/views/report/organisation_name.njk
- server/views/report/psc_name.njk
- test/server/routes/report.test.js
- Fetches PSC names from CHS and displays them
- Pushes selected PSC name to PSC service
> Feature/FAML-257: Add PSC name to service

- server/routes/report.js
- test/server/lib/Session.test.js
- Fixes the issues around duplication reported in QA
- Also stubs logger for the session handler
> Fix: Straighten out duplication issue in psc name list

- server/lib/errors/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- test/env.js
- test/server/routes/report.test.js
Check the company number provided for the discrepancy report against the company profile api and returns an error to the user if it does not exist.
Resolves: FAML-453
> Check company number exists

- server/routes/report.js
- server/services/psc_discrepancy.js
- server/views/report/oe_email.njk
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/routes/report.test.js
remove instances of telephone number in app
> change styling to match prototype

- package-lock.json
- package.json
A run of npm audit fix command.
> Ran npm audit fix

- server/views/report/confirmation.njk
> Update submission page to be inline with prototype

- Makefile
- package-lock.json
- package.json
Fix to get the coverage report to display be created.
> fix sonar coverage

- server/routes/report.js
- test/server/routes/report.test.js
Organisation name wasn't showing on failed validation. This is now fixed.
> Fix: Show organisation name on failed validation

- server/routes/report.js
- server/services/psc_discrepancy.js
- Ensure graceful error handling on cache miss for all handlers
- Fixes log message in service class when saving status
- Auto fixes linting errors
> Refactor: Handle cache misses gracefully

- server/views/report/confirmation.njk
> Update survey link

- package-lock.json
- package.json
- server/routes/report.js
- server/services/psc_discrepancy.js
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/services/psc_discrepancy.test.js
- Replaces deprecated `request-promise-native` with `axios`
- Refactors tests to be consistent with the changes
> Refactor/Faml-463: Replace http client

- server/routes/report.js
replaces the DoB acronym with full description in the view i.e. "Date of birth"
> refactor: replace acronym 'Dob' with full description

- server/views/report/psc_name.njk
Fixes issues with screen readers on PSC selection screen. 
Resolves FAML-519
> Update PSC selection descriptions for DOB to be unique

- server/views/report/company_number.njk
> Update company number page in-line with prototype

- server/routes/report.js
- server/views/report/company_confirmation.njk
- test/server/routes/report.test.js
Add a company confirmation page that displays company details after incorporation number has been entered. 
Resolves: FAML-559
> Add company confirmation page

- server/views/report/company_confirmation.njk
Resolves screen reader issues on company confirmation page
> Change the company confirmation page to use govuk list display instead of table

- package-lock.json
- package.json
- server/routes/report.js
- server/views/report/secure_psc.njk
- test/server/routes/report.test.js
> Add check to company profile API to see if a secure psc is present 

- server/lib/validation/index.js
- server/routes/report.js
- test/server/lib/validation/index.test.js
> Validate whitespace as empty string in webapp

- server/routes/report.js
> Add secureFlag only if companyProfileApi returns data

- server/routes/report.js
- server/views/report/check-your-answers.njk
- Along with the correct `get` route
- FAML-612
> Add new dummy page for check your answers 

- server/routes/report.js
- server/views/report/check-your-answers.njk
- test/server/_fakes/data/services/psc_discrepancy.js
- test/server/_fakes/mocks/lib/session.js
- test/server/routes/report.test.js
- Make page dynamic displaying data form db
- Allow data to be saved to backend
- Create new unit tests
> feature: Add check your answers page with all functionality

- server/lib/errors/error_manifest.js
- server/lib/validation/index.js
- server/routes/report.js
- server/routes/utils/index.js
- server/services/psc_discrepancy.js
- server/views/report/check-your-answers.njk
- server/views/report/psc_discrepancy_types.njk
- test/env.js
- test/server/_fakes/mocks/lib/session.js
- test/server/lib/validation/index.test.js
- test/server/routes/report.test.js
- test/server/routes/utils/index.test.js
- added psc discrepancy types page
- added routes (get and post) for psc discrepancy types
- added validation for the checkboxes
- added method to control what array is passed over to the page
- added tests for the routes and the new methods
- master branch was merged into this one
jira ticket: https://companieshouse.atlassian.net/browse/FAML-609
> Feature/fa 609  psc discrepancy types

- server/routes/report.js
- Now displays the textual equivalent on check your answers screen
> feature: change org type from numerical to text

- server/views/_layouts/default.njk
-change favicon icon from the crest to the crown
Jira Ticket (it has screenshot of icon): https://companieshouse.atlassian.net/browse/FAML-642
> PSC discrepancy - Favicon changes

- server/routes/report.js
- server/routes/utils/index.js
- server/views/report/check-your-answers.njk
- test/server/_fakes/mocks/lib/session.js
- test/server/routes/report.test.js
- test/server/routes/utils/index.test.js
feature:
-refactored code to redirect to details page for psc missing option
-refactored setDiscrepancyTypes method to handle kind inside the method
-fixed tests that broke and added a new route test for psc missing option
-added condition on check-your-answers.njk to hide pscDiscrepancyTypes if psc missing was selected
Jira Ticket : https://companieshouse.atlassian.net/browse/FAML-651
> PSC discrepancy - Implement PSC is missing journey

- server/views/_partials/phase_banner.njk
Update phase banner to show correct phase as beta.
https://companieshouse.atlassian.net/browse/FAML-645
> feature: update text on phase banner

- server/lib/errors/error_manifest.js
- server/routes/report.js
- server/views/report/psc_name.njk
- changed error message in error_manifest.js
- changed psc_name.njk to reflect the new heading
- changed title to reflect new title
- saved company name to the session
Jira Ticket: https://companieshouse.atlassian.net/browse/FAML-677
> faml-677 Heading change for 'Which PSC is incorrect' page

- server/views/_layouts/default.njk
- server/views/report/company_confirmation.njk
- server/views/report/contact_name.njk
- server/views/report/oe_type.njk
- server/views/report/organisation_name.njk
-add matomo scripts to report part of the journey
-add onclick events for the text entry to get the value
Jira ticket: https://companieshouse.atlassian.net/browse/FAML-660
> faml-660-matomo-psc-discrepancies-report
